name: "Deploy infrastucture"

on:
  push:
    branches:
      - main
    paths:
      - "**.tf"
      - ".github/workflows/terraform.yaml"
  workflow_dispatch:

concurrency: terraform

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_USE_OIDC: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log into Azure using OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2

      - name: Terraform Init
        run: |
          terraform init \
          -backend-config=storage_account_name=${{ secrets.BACKEND_STORAGE_ACCOUNT_NAME}} \
          -backend-config=container_name=${{ secrets.BACKEND_STORAGE_CONTAINER_NAME}} \
          -backend-config=resource_group_name=${{ secrets.BACKEND_STORAGE_RESOURCE_GROUP_NAME}}
        working-directory: deploy

      - name: Terraform Plan
        run: terraform plan -out=plan.tfplan
        working-directory: deploy

      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve plan.tfplan
        working-directory: deploy
